# Índice {-}

 *Prefacio*
 
 *Capítulo 1: Introducción al análisis de datos con R *
 
1.1. 	Objetivos de aprendizaje

1.2.	Configuración del directorio

1.3.	Importación de datos

1.4.	Estudio de caso: La mortalidad en el Perú en el contexto de la pandemia por la COVID-19

1.5.	Limpieza de datos 

1.6.	Manipulación de la base de datos

 *Capítulo 2: Estadística Descriptiva *
 
2.1.	 Objetivos de aprendizaje 

2.2.	Instalación y carga de paquetes

2.3.	Estudio de caso: Mortalidad por semana epidemiológica en el Perú
2.4.	Exploración de datos

2.5.	Medidas de tendencia central

2.6.	Medidas de dispersión

2.7.	Análisis de normalidad 

2.8.	Gráficos

2.9.	Clustering

 *Capítulo 3: Prueba de Hipótesis y Análisis Bivariado *
 
3.1.	Objetivos de aprendizaje 

3.2.	Estudio de caso: Beneficios y complicaciones del uso de la técnica Nyhus con la técnica de Lichtenstein en el tratamiento de las hernias inguinales

3.3.	Pruebas de hipótesis

3.4.	Comparación de dos medias de muestras independientes

3.5.	Comparación de dos proporciones de muestras independientes
3.6.	Comparación de dos medias de muestras pareadas

3.7.	Comparación de dos proporciones de muestras pareadas

3.8.	Correlación

3.9.	Prueba binomial

*Capítulo 4: Regresión Lineal *

4.1.	 Objetivos de aprendizaje 

4.2.	Estudio de caso: Pruebas en carretera de automóviles de Motor Trend

4.3.	Análisis de correlación

4.4.	Modelos de regresión

4.5.	Intervalos de confianza

4.6.	Análisis post regresión

 *Capítulo 5: Regresión Logística *
 
 
5.1.	 Objetivos de aprendizaje 

5.2.	Estudio de caso: Introducción de especies de aves en Nueva Zelanda

5.3.	Análisis descriptivo 

5.4.	Análisis de correlación

5.5.	Modelo de regresión logística

5.6.	Análisis post regresión

 *Capítulo 6: Regresión de Poisson *
 
6.1.	Objetivos de aprendizaje

6.2.	Estudio de caso: Incentivos a estudiantes de una escuela secundaria

6.3.	Análisis descriptivo

6.4.	Análisis de correlación

6.5.	Modelos de regresión de Poisson

6.6.	Desviaciones para comparar modelos 

6.7.	Análisis post regresión

6.8.	Predicción del modelo

 *Capítulo 7: Regresión Binomial *
 
7.1.	Objetivos de aprendizaje

7.2.	Estudio de caso: Introducción de especies de aves en Nueva Zelanda

7.3.	Análisis de correlación

7.4.	Data seleccionada

7.5.	Regresión binomial

7.6.	Análisis post regresión

7.7.	Grado de coeficientes

7.8.	Graficando los efectos

 *Capítulo 8: Regresión de Cox *
 
8.1.	Objetivos de aprendizaje 

8.2.	Estudio de caso: Supervivencia en pacientes con cáncer de pulmón avanzado

8.3.	Análisis descriptivo

8.4.	Análisis de supervivencia

8.5.	Kaplan – Meier (KM)

8.6.	Regresión múltiple 

8.7.	Análisis post regresión

8.8.	Visualización de la distribución estimada de los tiempos de supervivencia
